# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f05d20ac3099cf86ca1cca40712b0892d366698a7e8d0fa8355c226a9fe4df7cfe0ba9e619018bf87d73445eae6e2b7ef347fa13e062a9d0bc3db2b9f57e4be1

test:
  secret_key_base: 8d0e51d02cd07a97bf6bfcc9fd96af46cade9022259fe7395225932a08e7ec7afb6200fa8695000dc63b286f6dce35749a80807df1ed115b27289721bbf0fb63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
